theme: jekyll-theme-slate
title: WCAG 2.0 Parsing Validation Tools
description: Tools that filter the results of the W3Câ€™s Nu validator to show only results that are related to accessibility according to WCAG 2.0 Success Criterion 4.1.1 Parsing.
